# Generated by Django 3.1.5 on 2021-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsertionModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('textfield', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
