# Generated by Django 3.1.5 on 2021-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionmodel',
            name='image',
            field=models.FileField(default=False, upload_to='media/'),
        ),
    ]
