# Generated by Django 3.1.5 on 2021-02-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_insertionmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionmodel',
            name='title',
            field=models.TextField(default=False),
        ),
    ]
