# Generated by Django 3.1.5 on 2021-02-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_insertionmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertionmodel',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='insertionmodel',
            name='textfield',
            field=models.CharField(max_length=1000),
        ),
    ]
